<link rel="stylesheet" href="<?= $wwwUrl ?>/css/admin.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/connect.css">

<a href="<?= $requestUrl ?>/users/admin"><button type="button" name="button" class="btn btn-back">Retour</button></a>
<h2 class="title title-page">Produits</h2>
<table class='admin-table'>
  <thead>
    <tr>
      <th>Photo</th>
      <th>Nom</th>
      <th>Type</th>
      <th>Prix d'achat</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
      <?php foreach ($products as $product): ?>
          <tr>
        <td><img src="<?= $wwwUrl ?>/images/pc/buy/<?= $product['Photo'] ?>" alt=""></td>
        <td><?= $product['Name'] ?></td>
        <td><?= $product['ProductLine'] ?></td>
        <td><?= $product['BuyPrice'] ?> €</td>
        <td>
          <div class="action">
          <a href="<?= $requestUrl ?>/users/admin/products/delete?id=<?=$product['Id']?>"><button class="trash draw-outline draw-outline--tandem"><i class="fas fa-trash-alt"></i></button></a>
          <a href="<?= $requestUrl ?>/users/admin/products/update?id=<?=$product['Id']?>"><button class="draw-outline draw-outline--tandem"><i class="fas fa-pen"></i></button></a>
        </div>
        </td>
      </tr>
      <?php endforeach; ?>
  </tbody>
</table>
<div class="add">
  <i class="fas fa-plus-circle"></i>
  <div class="add-element move">
    <div id="contact">
      <h2>Ajoutez une catégorie !</h2>
      <div class="content">
        <div id="form">
          <form id="contactForm" action="<?= $requestUrl ?>/users/admin/products" method="post" enctype="multipart/form-data">
            <span>Name</span>
            <input type="text" name="name" class="name" placeholder="Nom de du produit" tabindex=1 required />
            <span>Photo</span>
            <input type="file" name="photo" class="email" tabindex=2 />
            <span>Type</span>
            <input type="text" name="type" class="captcha" placeholder="Type" tabindex=3 required />
            <span>Description</span>
            <textarea class="message" name="description" placeholder="Description" tabindex=4></textarea>
            <span>Quantité</span>
            <input type="text" name="quantityInStock" class="captcha" placeholder="Quantité" tabindex=5 required />
            <span>Prix d'achat</span>
            <input type="text" name="buyprice" class="captcha" placeholder="Prix d'achat" tabindex=6 required />
            <span>Prix de vente</span>
            <input type="text" name="saleprice" class="captcha" placeholder="Prix de vente" tabindex=7 required />
            <span>Réduction</span>
            <input type="text" name="reduction" class="captcha" placeholder="reduction (en %)" tabindex=8 required />
            <div class="form__field">
              <button class="btn btn-back" type="submit">Ajouter</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
<script src="<?= $wwwUrl ?>/js/admin.js"></script>
