<link rel="stylesheet" href="<?= $wwwUrl ?>/css/admin.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/connect.css">

<a href="<?= $requestUrl ?>/users/admin"><button type="button" name="button" class="btn btn-back">Retour</button></a>
<h2 class="title title-page">Produits</h2>
<table class='admin-table'>
  <thead>
    <tr>
      <th>Photo</th>
      <th>Nom</th>
      <th>Type</th>
      <th>Prix d'achat</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
      <?php foreach ($products as $product): ?>
          <tr>
        <td><img src="<?= $wwwUrl ?>/images/pc/buy/<?= $product['Photo'] ?>" alt=""></td>
        <td><?= $product['Name'] ?></td>
        <td><?= $product['ProductLine'] ?></td>
        <td><?= $product['BuyPrice'] ?> €</td>
        <td>
          <div class="action">
          <a href="<?= $requestUrl ?>/users/admin/products/delete?id=<?=$product['Id']?>"><button class="trash draw-outline draw-outline--tandem"><i class="fas fa-trash-alt"></i></button></a>
          <a href="<?= $requestUrl ?>/users/admin/products/update?id=<?=$product['Id']?>"><button class="draw-outline draw-outline--tandem"><i class="fas fa-pen"></i></button></a>
        </div>
        </td>
      </tr>
      <?php endforeach; ?>
  </tbody>
</table>
<div class="add">
  <i class="fas fa-plus-circle"></i>
  <div class="add-element move">
    <div class="align">
      <h2>Ajoutez un produit !</h2>
      <div class="grid">
        <form class="form login" action="<?= $requestUrl ?>/users/admin/products" method="post" enctype="multipart/form-data">
          <div class="form__field">
            <label for="login__username">name</label>
            <input type="text" id="login__username" class="form__input" name="name" placeholder="Nom du produit" required>
          </div>
          <div class="form__file">
            <label for="login__lastname">photo</label>
            <input type="file" id="login__lastname" class="form__input" name="photo" type="file" required>
          </div>
          <div class="form__field">
            <label for="login__email">type</label>
            <input type="text" id="login__email" class="form__input" name="type" placeholder="Type" required>
          </div>
          <div class="form__field">
            <label for="login__email">description</label>
            <textarea rows="10" cols="80" id="login__email" class="form__input" name="description" placeholder="Description" required></textarea>
          </div>
          <div class="form__field">
            <label for="login__email">quantité</label>
            <input type="text" id="login__email" class="form__input" name="quantityInStock" placeholder="Quantité" required>
          </div>
          <div class="form__field">
            <label for="login__pseudo">prix d'achat</label>
            <input type="text" id="login__pseudo" class="form__input" name="buyprice" placeholder="Prix d'achat" required>
          </div>
          <div class="form__field">
            <label for="login__email">prix de vente</label>
            <input type="text" id="login__email" class="form__input" name="saleprice" placeholder="Prix de vente" required>
          </div>
          <div class="form__field">
            <label for="login__password">reduction</label>
            <input id="login__password" type="text" name="reduction" class="form__input" placeholder="reduction (en %)" required>
          </div>
          <div class="form__field">
            <button class="cross-fade" type="submit">Ajouter</button>
          </div>
        </form>
      </div>
    </div>

  </div>
</div>
<script src="<?= $wwwUrl ?>/js/admin.js"></script>
