<link rel="stylesheet" href="<?= $wwwUrl ?>/css/connect.css">

<a href="<?= $requestUrl ?>/users/admin/categories"><button type="button" name="button" class="btn btn-back">Retour</button></a>
<div class="align">
  <div class="grid">
    <form class="form login" action="<?= $requestUrl ?>/users/admin/categories/update" method="post" enctype="multipart/form-data">
      <div class="form__field">
        <label for="login__username">productline</label>
        <input type="text" id="login__username" class="form__input" name="productline" placeholder="Type" value="<?= $line['productLine'] ?>" >
      </div>
      <div class="form__file">
        <label for="login__lastname">image</label>
        <input type="file" id="login__lastname" class="form__input" name="image" type="file">
      </div>
      <div class="form__field">
        <label for="login__email">description</label>
        <textarea rows="10" cols="80" id="login__email" class="form__input" name="resume" placeholder="Description" >"<?= $line['Resume'] ?>"</textarea>
      </div>
      <div class="form__field">
        <label for="login__password">Title</label>
        <input id="login__password" type="text" name="title" class="form__input" placeholder="titre" value="<?= $line['Title'] ?>" >
      </div>
      <input type="hidden" name="id" value="<?= $line['Id'] ?>">
      <div class="form__field">
        <button class="cross-fade" type="submit">Modifier</button>
      </div>
    </form>
  </div>
</div>
