<link rel="stylesheet" href="<?= $wwwUrl ?>/css/admin.css">

<h2 class="title title-page">Administration</h2>
<div class="admin-view">
  <div class="management user-management">
    <h3>User Management</h3>
    <div class="admin use">
      <h4 class="title title-management"><a href="<?= $requestUrl ?>/users/admin/account"><i class="fas fa-user-friends"></i> Utilisateurs</h4></a>
    </div>
  </div>
  <div class="management product-management">
    <h3>Product Management</h3>
    <div class="admin products">
      <h4 class="title title-management"><a href="<?= $requestUrl ?>/users/admin/products"><i class="fas fa-store-alt"></i> Produits</h4></a>
    </div>
    <div class="admin orders">
      <h4 class="title title-management"><a href="<?= $requestUrl ?>/users/admin/orders"><i class="fas fa-clipboard-list"></i> Commandes</h4></a>
    </div>
  </div>
  <div class="management category-management">
    <h3>Category Management</h3>
    <div class="admin category">
      <h4 class="title title-management"><a href="<?= $requestUrl ?>/users/admin/categories"><i class="fas fa-list-ul"></i> Categories</h4></a>
    </div>
  </div>
</div>
