<link rel="stylesheet" href="<?= $wwwUrl ?>/css/admin.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/connect.css">

<a href="<?= $requestUrl ?>/users/admin"><button type="button" name="button" class="btn btn-back">Retour</button></a>
<h2 class="title title-page">Catégories</h2>
<table class='admin-table categories-table'>
  <thead>
    <tr>
      <th>Photo</th>
      <th>Nom</th>
      <th>Type</th>
      <th>Description</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <?php foreach ($lines as $line): ?>
      <tr>
        <td class="td-image"><img src="<?= $wwwUrl ?>/images/pc/lines/<?= $line['Image'] ?>" alt=""></td>
        <td><?= $line['productLine'] ?></td>
        <td><?= $line['Title'] ?></td>
        <td><?= $line['Resume'] ?></td>
        <td>
          <div class="action">
            <a href="<?= $requestUrl ?>/users/admin/categories/update?id=<?=$line['Id']?>"><button class="draw-outline draw-outline--tandem"><i class="fas fa-pen"></i></button></a>
          </div>
        </td>
      </tr>
    <?php endforeach; ?>
  </tbody>
</table>
<div class="add">
  <i class="fas fa-plus-circle"></i>
  <div class="add-element move">
    <div id="contact">
      <h2>Ajoutez une catégorie !</h2>
      <div class="content">
        <div id="form">
          <form id="contactForm" action="<?= $requestUrl ?>/users/admin/categories" method="post" enctype="multipart/form-data">
            <span>Line</span>
            <input type="text" name="productline" class="name" placeholder="Nom de la catégorie" tabindex=1 required />
            <span>Image</span>
            <input type="file" name="image" class="email" tabindex=2 />
            <span>Type</span>
            <input type="text" name="type" class="captcha" placeholder="Type" tabindex=3 required />
            <span>Description</span>
            <textarea class="message" name="resume" placeholder="Description" tabindex=4></textarea>
            <div class="form__field">
              <button class="btn btn-back" type="submit">Ajouter</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
