<link rel="stylesheet" href="<?= $wwwUrl ?>/css/admin.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/connect.css">

<a href="<?= $requestUrl ?>/users/admin"><button type="button" name="button" class="btn btn-back">Retour</button></a>
<h2 class="title title-page">Produits</h2>
<table class='admin-table'>
  <thead>
    <tr>
      <th>Photo</th>
      <th>Nom</th>
      <th>Type</th>
      <th>Description</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
      <?php foreach ($lines as $line): ?>
          <tr>
        <td><img src="<?= $wwwUrl ?>/images/pc/lines/<?= $line['Image'] ?>" alt=""></td>
        <td><?= $line['productLine'] ?></td>
        <td><?= $line['Title'] ?></td>
        <td><?= $line['Resume'] ?></td>
        <td>
          <div class="action">
          <a href="<?= $requestUrl ?>/users/admin/categories/update?id=<?=$line['Id']?>"><button class="draw-outline draw-outline--tandem"><i class="fas fa-pen"></i></button></a>
        </div>
        </td>
      </tr>
      <?php endforeach; ?>
  </tbody>
</table>
<div class="add">
  <i class="fas fa-plus-circle"></i>
  <div class="add-element move">
    <div class="align">
      <h2>Ajoutez une catégorie !</h2>
      <div class="grid">
        <form class="form login" action="<?= $requestUrl ?>/users/admin/categories" method="post" enctype="multipart/form-data">
          <div class="form__field">
            <label for="login__username">line</label>
            <input type="text" id="login__username" class="form__input" name="productline" placeholder="Nom de la catégorie" required>
          </div>
          <div class="form__file">
            <label for="login__lastname">image</label>
            <input type="file" id="login__lastname" class="form__input" name="image" type="file">
          </div>
          <div class="form__field">
            <label for="login__email">type</label>
            <input type="text" id="login__email" class="form__input" name="type" placeholder="Type" required>
          </div>
          <div class="form__field">
            <label for="login__email">description</label>
            <textarea rows="10" cols="80" id="login__email" class="form__input" name="resume" placeholder="Description" required></textarea>
          </div>
          <div class="form__field">
            <button class="cross-fade" type="submit">Ajouter</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
