<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
  <title>Computer Buying Pro</title>
  <link rel="stylesheet" href="<?= $wwwUrl ?>/css/normalize.css">
  <link rel="stylesheet" href="<?= $wwwUrl ?>/css/button.css">
  <link rel="stylesheet" href="<?= $wwwUrl ?>/css/style.css">
  <link href="https://fonts.googleapis.com/css?family=Dosis&display=swap" rel="stylesheet">
  <script src="https://kit.fontawesome.com/a076d05399.js"></script>
  <script
  src="https://code.jquery.com/jquery-3.4.1.min.js"
  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
  crossorigin="anonymous"></script>

  <!-- JavaScript de l'application -->
  <script src="<?= $wwwUrl ?>/js/classes/Basket.class.js"></script>
  <script src="<?= $wwwUrl ?>/js/utilities.js"></script>
</head>
<body id="top">
  <header class="header-main">
    <img class="header-logo" src="<?= $wwwUrl ?>/images/logo/logo.png" alt="logo">
    <h1 class="title title-main">Computer Buying Pro</h1>
  </header>
  <nav class="nav-main">
    <ul class="nav-list">
      <li class="element"> <a href="<?= $requestUrl ?>/">Accueil</a> </li>
        <li class="element under-list products"> <a href="<?= $requestUrl ?>/products">Nos produits</a></li>
      <div class="element-hide">
        <?php if(array_key_exists('role', $_SESSION) === true){ ?>
          <?php if($_SESSION["role"] === "user"){ ?>
            <li class="element under-list users"><i class="fas fa-user"></i> <i class="fas fa-sort-down"></i>
              <ul class="second-list hide user">
              <?php }elseif($_SESSION["role"] === "premium"){ ?>
                <li class="element under-list users"><i class="fas fa-user-tie"></i> <i class="fas fa-sort-down"></i>
                  <ul class="second-list hide user">
                  <?php }elseif($_SESSION["role"] === "admin"){ ?>
                    <li class="element under-list users"><i class="fas fa-user-md"></i> <i class="fas fa-sort-down"></i>
                      <ul class="second-list hide user">
                        <li class="element"> <a href="<?= $requestUrl ?>/users/admin">Admin</a> </li>
                      <?php } ?>
                      <li class="element"> <a href="<?= $requestUrl ?>/users/profil">Profil</a> </li>
                      <li class="element"> <a href="<?= $requestUrl ?>/users/logout">Se déconnecter <i class="fas fa-sign-out-alt"></i></a> </li>
                    </ul>
                  </li>
                <?php }else{ ?>
                  <li class="element under-list users"><i class="fas fa-user"></i> <i class="fas fa-sort-down"></i>
                    <ul class="second-list hide user">
                      <li class="element"> <a href="<?= $requestUrl ?>/users/login"><i class="fas fa-sign-in-alt"></i> Se connecter</a> </li>
                      <li class="element"> <a href="<?= $requestUrl ?>/users/register">S'enregistrer</i></a> </li>
                    </ul>
                  </li>
                 <?php } ?>
              </div>
      <div class="element-hide">
        <li class="element under-list contacts">Nous contacter <i class="fas fa-sort-down"></i>
          <ul class="second-list hide contact">
            <li class="element"> <a href='https://www.twitter.com'><i class="fab fa-twitter-square"></i></a> </li>
            <li class="element"> <a href='https://www.facebook.com'><i class="fab fa-facebook-square"></i></a> </li>
            <li class="element"> <a href='https://www.instagram.com'><i class="fab fa-instagram"></i></a> </li>
            <li class="element"> <a href='https://www.linkedin.com'><i class="fab fa-linkedin"></i></a> </li>
          </ul>
        </li>
      </div>
      <li class="element">
        <a href="<?= $requestUrl ?>/basket"><i class="fas fa-shopping-cart"></i></a>
        <em class="hide" id="itemBasket"></em>
     </li>
    </ul>
  </nav>
  <nav class="nav-bar-mobile">
        <i class="fas fa-bars" id="burger-button"></i>
        <div class="nav-column move-aside">
          <a class='list-item' href='<?= $requestUrl ?>'>
            <i class="fas fa-home"></i>
          </a>
          <a class='list-item' href='<?= $requestUrl ?>/products'>
            <i class="fas fa-store"></i>
          </a>
          <?php if (array_key_exists('role', $_SESSION) === false){ ?>
            <a class='list-item' href='<?= $requestUrl ?>/users/login'>
              <i class="fas fa-user"></i>
            </a>
          <?php }else{ ?>
            <?php if ($_SESSION['role'] === 'admin'){ ?>
              <a class='list-item' href='<?= $requestUrl ?>/users/admin'>
                <i class="fas fa-user-shield"></i>
              </a>
            <?php } ?>
            <a class='list-item' href='<?= $requestUrl ?>/users/profil'>
              <i class="fas fa-id-card"></i>
            </a>
            <a class='list-item' href='<?= $requestUrl ?>/basket'>
              <i class="fas fa-shopping-basket"></i>
            </a>
            <a class='list-item' href='<?= $requestUrl ?>/users/logout'>
              <i class="fas fa-sign-out-alt"></i>
            </a>
          <?php } ?>
          <a class='list-item' href='https://www.instagram.com'>
            <i class="fab fa-instagram"></i>
          </a>
          <a class='list-item' href='https://www.facebook.com'>
            <i class="fab fa-facebook-f"></i>
          </a>
          <a class='list-item' href='https://twitter.com'>
            <i class="fab fa-twitter"></i>
          </a>
          <a class='list-item' href='https://linkedin.com'>
            <i class="fab fa-linkedin"></i>
          </a>
        </div>
      </nav>
  <main class="container">
    <?php include $this->viewData['template']; ?>
    <div id="productPopUp" class="popUp hide">
      <p id="closePopUpProduct" class="closePopUp">X</p>
      <h4>Félicitation !</h4>
      <p>Vous avez ajouté <em id="elementNumber"></em> produit(s) à votre panier</p>
      <img src="<?= $wwwUrl ?>/images/logo/pop/yes.png" alt="addict">
      <button type="button" class="closePopUp draw-outline draw-outline--tandem">Retour aux achats</button>
    </div>

    <div id="errorPopUp" class="popUp hide">
      <p id="closePopUpError" class="closePopUp">X</p>
      <h4>PROBLEME!</h4>
      <p>Vous ne pouvez pas rajouter 0 quantité !!</p>
      <img src="<?= $wwwUrl ?>/images/logo/pop/no.png" alt="addict">
      <button type="button" class="closePopUp draw-outline draw-outline--tandem">Retour aux achats</button>
    </div>
  </main>
  <footer class="footer-main">
    Copyright (c) 2020 Copyright Holder All Rights Reserved.
    <a href="#top" class="top"><i class="fas fa-arrow-alt-circle-up"></i></a>
  </footer>
  <script type="text/javascript" src="<?= $wwwUrl ?>/js/main.js"></script>
</body>
</html>
