<link rel="stylesheet" href="<?= $wwwUrl ?>/css/connect.css">

<a href="<?= $requestUrl ?>/users/admin/products"><button type="button" name="button" class="btn btn-back">Retour</button></a>
<div class="align">
  <h2>Modifiez ce produit !</h2>
  <div class="grid">
    <form class="form login" action="<?= $requestUrl ?>/users/admin/products/update" method="post" enctype="multipart/form-data">
      <div class="form__field">
        <label for="login__username">name</label>
        <input type="text" id="login__username" class="form__input" name="name" placeholder="Nom du produit" value="<?= $product['Name'] ?>" required>
      </div>
      <div class="form__file">
        <label for="login__lastname">photo</label>
        <input type="file" id="login__lastname" class="form__input" name="photo" type="file">
      </div>
      <div class="form__field">
        <label for="login__email">description</label>
        <textarea rows="10" cols="80" id="login__email" class="form__input" name="description" placeholder="Description" required>"<?= $product['Description'] ?>"</textarea>
      </div>
      <div class="form__field">
        <label for="login__email">quantité</label>
        <input type="text" id="login__email" class="form__input" name="quantityInStock" placeholder="Quantité" value="<?= $product['QuantityInStock'] ?>" required>
      </div>
      <div class="form__field">
        <label for="login__pseudo">prix d'achat</label>
        <input type="text" id="login__pseudo" class="form__input" name="buyprice" placeholder="Prix d'achat" value="<?= $product['BuyPrice'] ?>" required>
      </div>
      <div class="form__field">
        <label for="login__email">prix de vente</label>
        <input type="text" id="login__email" class="form__input" name="saleprice" placeholder="Prix de vente" value="<?= $product['SalePrice'] ?>" required>
      </div>
      <div class="form__field">
        <label for="login__password">reduction</label>
        <input id="login__password" type="text" name="reduction" class="form__input" placeholder="reduction (en %)" value="<?= $product['Reduction'] ?>" required>
      </div>
      <input type="hidden" name="id" value="<?= $product['Id'] ?>">
      <div class="form__field">
        <button class="cross-fade" type="submit">Modifier</button>
      </div>
    </form>
  </div>
</div>
