<link rel="stylesheet" href="<?= $wwwUrl ?>/css/connect.css">

<div class="align">
  <h2>Connectez vous !</h2>
  <?php if ($error != null) { ?>
    <small><?= $error ?></small>
  <?php } ?>
  <div class="grid">
    <form class="form login" action="<?= $requestUrl ?>/users/login" method="post">
      <div class="form__field">
        <label for="login__username"><i class="fas fa-user-alt"></i><span class="hidden">Username</span></label>
        <input id="login__username" type="text" name="email" class="form__input" placeholder="Email / Pseudo" required>
      </div>

      <div class="form__field">
        <label for="login__password"><i class="fas fa-lock"></i> <span class="hidden">Password</span></label>
        <input id="login__password" type="password" name="password" class="form__input" placeholder="mot de passe" required>
      </div>
      <div class="form__field">
        <button class="cross-fade" type="submit">Let's go</button>
      </div>
    </form>
  </div>
</div>
