<link rel="stylesheet" type="text/css" href="<?= $wwwUrl ?>/css/payment.css">

<h3>Paiement de votre commande</h3>
<div class="container">
  <form class="p-form" action="<?= $requestUrl ?>/payment/charge" method="post" id="payment-form">
    <input type="hidden" name="orders" value="computerBasket" id="orders">
    <div class="form-row">
      <div id="card-element" class="form-control ">
      </div>
      <div id="card-errors" role="alert"></div>
    </div>
    <button type="submit" name="Payer" class="cross-fade">Payer</button>
  </form>
</div>
<script src="https://js.stripe.com/v3/"></script>
<script type="text/javascript" src="<?= $wwwUrl ?>/js/charge.js"></script>
