<link rel="stylesheet" href="<?= $wwwUrl ?>/css/connect.css">

<a href="<?= $requestUrl ?>/users/admin/account"><button type="button" name="button" class="btn btn-back">Retour</button></a>
<div class="align">
  <h2><?= mb_strtoupper($user['Pseudo']) ?></h2>
  <div class="grid">
    <form class="form login" action="" method="post">
      <div class="form__field">
        <label for="login__username"><i class="fas fa-user-alt"></i><span class="hidden">firstname</span></label>
        <input type="text" id="login__username" class="form__input" name="firstname" value="<?= $user['FirstName'] ?>" readonly>
      </div>
      <div class="form__field">
        <label for="login__lastname"><i class="fas fa-user-alt"></i><span class="hidden">lastname</span></label>
        <input type="text" id="login__lastname" class="form__input" name="lastname" value="<?= $user['LastName'] ?>" readonly>
      </div>
      <div class="form__field">
        <label for="login__pseudo"><i class="fas fa-user-alt"></i><span class="hidden">pseudo</span></label>
        <input type="text" id="login__pseudo" class="form__input" name="pseudo" value="<?= $user['Pseudo'] ?>" readonly>
      </div>
      <div class="form__field">
        <label for="login__pseudo"><i class="fas fa-user-alt"></i><span class="hidden">pseudo</span></label>
        <input type="text" id="login__pseudo" class="form__input" name="email" value="<?= $user['Email'] ?>" readonly>
      </div>
      <div class="form__field">
        <label for="login__address"><i class="fas fa-home"></i><span class="hidden">adresse</span></label>
        <input type="text" id="login__address" class="form__input" name="address" value="<?= $user['Address'] ?>" readonly>
      </div>
      <div class="form__field">
        <label for="login__city"><i class="fas fa-city"></i><span class="hidden">city</span></label>
        <input type="text" id="login__city" class="form__input" name="city" value="<?= $user['City'] ?>" readonly>
      </div>
      <div class="form__field">
        <label for="login__zip"><span class="hidden">zip</span></label>
        <input type="text" id="login__zip" class="form__input" name="zip" value="<?= $user['Zip'] ?>" readonly>
      </div>
    </form>
  </div>
</div>
