<link rel="stylesheet" href="<?= $wwwUrl ?>/css/products.css">

<a href="<?= $requestUrl ?>/products"><button type="button" name="button" class="btn btn-back">Retour</button></a>
<?php if (empty($_GET['result'])): ?>
  <h2 class="title title-page">Resultats pour <br>"<?= $_POST['search'] ?>"</br></h2>
<?php elseif(empty($_POST['search'])):?>
  <h2 class="title title-page">Les <?= $line['Title'] ?></h2>
<?php endif; ?>
<?php if (empty($line) === false): ?>
  <p><?= $line['Resume'] ?></p>
<?php endif; ?>

<?php if (empty($products)){ ?>
  <p>Il n'y pas encore de produits ici...</p>
<?php }else{ ?>
  <ul class="products">
  <?php if(array_key_exists('role', $_SESSION) === false || $_SESSION['role'] === "user"): ?>
    <?php foreach ($products as $product): ?>
      <div class="product-list">
      <a href="<?= $requestUrl ?>/products/product?id=<?= $product['Id'] ?>">
        <li><img src="<?= $wwwUrl ?>/images/pc/buy/<?= $product['Photo'] ?>" alt=""></li>
        <li><?= $product['Name'] ?></li>
      </a>
      <li>
        Prix de base = <strong><?= $product['SalePrice'] ?>€</strong>
        <form class="basket-form" action="<?= $requestUrl ?>/products/search">
          <input type="number" name="quantity" id="product-<?=$product['Id']?>">
          <button class="addToBasket draw-outline draw-outline--tandem" data-name="<?=$product['Name']?>" data-price="<?=$product['SalePrice']?>" data-id="<?=$product['Id']?>"><p>Ajouter au panier</p></button>
        </form>
      </li>
      </div>
    <?php endforeach; ?>
  <?php elseif ($_SESSION['role'] === "premium" || $_SESSION['role'] === "admin"): ?>
      <?php foreach ($reducs as $reduc): ?>
        <div class="product-list">
          <a href="<?= $requestUrl ?>/products/product?id=<?= $reduc['Id'] ?>">
            <li><img src="<?= $wwwUrl ?>/images/pc/buy/<?= $reduc['Photo'] ?>" alt=""></li>
            <li><?= $reduc['Name'] ?></li>
          </a>
          <?php if ($reduc['Reduction'] <= 0) {?>
          <li>Prix de base = <strong><?= $reduc['SalePrice'] ?>€</strong></li>
        <?php }elseif ($reduc['Reduction'] > 0) { ?>
            <li>Prix de base = <span class="over"><strong><?= $reduc['SalePrice'] ?>€</strong></span></li>
              <li>Reduction de <?=$reduc['Reduction']?>% : <strong><?= number_format($reduc['reduc'],2) ?>€</strong></li>
          <?php } ?>
            <form class="basket-form">
              <input type="number" name="quantity" id="product-<?=$reduc['Id']?>">
              <button class="addToBasket draw-outline draw-outline--tandem" data-name="<?=$reduc['Name']?>" data-price="<?=$reduc['reduc']?>" data-id="<?=$reduc['Id']?>"><p>Ajouter au panier</p></button>
            </form>
          </li>
        </div>
      <?php endforeach; ?>
    <?php endif; ?>
  </ul>
<?php } ?>
